#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
cd ${OPENSHIFT_REPO_DIR}
nohup mvn --quiet -Dmaven.repo.local=${OPENSHIFT_DATA_DIR}maven -Djetty.host=$OPENSHIFT_INTERNAL_IP -Djetty.port=$OPENSHIFT_INTERNAL_PORT org.mortbay.jetty:jetty-maven-plugin:start >${OPENSHIFT_LOG_DIR}/jetty.log 2>&1 &
