// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.h4mu.kontroll.domain;

import io.github.h4mu.kontroll.domain.Checkin;
import io.github.h4mu.kontroll.domain.CheckinDataOnDemand;
import io.github.h4mu.kontroll.domain.CheckinIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CheckinIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CheckinIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CheckinIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CheckinIntegrationTest: @Transactional;
    
    @Autowired
    CheckinDataOnDemand CheckinIntegrationTest.dod;
    
    @Test
    public void CheckinIntegrationTest.testCountCheckins() {
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", dod.getRandomCheckin());
        long count = Checkin.countCheckins();
        Assert.assertTrue("Counter for 'Checkin' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CheckinIntegrationTest.testFindCheckin() {
        Checkin obj = dod.getRandomCheckin();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to provide an identifier", id);
        obj = Checkin.findCheckin(id);
        Assert.assertNotNull("Find method for 'Checkin' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Checkin' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CheckinIntegrationTest.testFindAllCheckins() {
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", dod.getRandomCheckin());
        long count = Checkin.countCheckins();
        Assert.assertTrue("Too expensive to perform a find all test for 'Checkin', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Checkin> result = Checkin.findAllCheckins();
        Assert.assertNotNull("Find all method for 'Checkin' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Checkin' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CheckinIntegrationTest.testFindCheckinEntries() {
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", dod.getRandomCheckin());
        long count = Checkin.countCheckins();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Checkin> result = Checkin.findCheckinEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Checkin' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Checkin' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CheckinIntegrationTest.testFlush() {
        Checkin obj = dod.getRandomCheckin();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to provide an identifier", id);
        obj = Checkin.findCheckin(id);
        Assert.assertNotNull("Find method for 'Checkin' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCheckin(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Checkin' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CheckinIntegrationTest.testMergeUpdate() {
        Checkin obj = dod.getRandomCheckin();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to provide an identifier", id);
        obj = Checkin.findCheckin(id);
        boolean modified =  dod.modifyCheckin(obj);
        Integer currentVersion = obj.getVersion();
        Checkin merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Checkin' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CheckinIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", dod.getRandomCheckin());
        Checkin obj = dod.getNewTransientCheckin(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Checkin' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Checkin' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Checkin' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CheckinIntegrationTest.testRemove() {
        Checkin obj = dod.getRandomCheckin();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Checkin' failed to provide an identifier", id);
        obj = Checkin.findCheckin(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Checkin' with identifier '" + id + "'", Checkin.findCheckin(id));
    }
    
}
