// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.h4mu.kontroll.domain;

import io.github.h4mu.kontroll.domain.Stop;
import io.github.h4mu.kontroll.domain.StopDataOnDemand;
import io.github.h4mu.kontroll.domain.StopIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect StopIntegrationTest_Roo_IntegrationTest {
    
    declare @type: StopIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: StopIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: StopIntegrationTest: @Transactional;
    
    @Autowired
    StopDataOnDemand StopIntegrationTest.dod;
    
    @Test
    public void StopIntegrationTest.testCountStops() {
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", dod.getRandomStop());
        long count = Stop.countStops();
        Assert.assertTrue("Counter for 'Stop' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void StopIntegrationTest.testFindStop() {
        Stop obj = dod.getRandomStop();
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stop' failed to provide an identifier", id);
        obj = Stop.findStop(id);
        Assert.assertNotNull("Find method for 'Stop' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Stop' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void StopIntegrationTest.testFindAllStops() {
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", dod.getRandomStop());
        long count = Stop.countStops();
        Assert.assertTrue("Too expensive to perform a find all test for 'Stop', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Stop> result = Stop.findAllStops();
        Assert.assertNotNull("Find all method for 'Stop' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Stop' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void StopIntegrationTest.testFindStopEntries() {
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", dod.getRandomStop());
        long count = Stop.countStops();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Stop> result = Stop.findStopEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Stop' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Stop' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void StopIntegrationTest.testFlush() {
        Stop obj = dod.getRandomStop();
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stop' failed to provide an identifier", id);
        obj = Stop.findStop(id);
        Assert.assertNotNull("Find method for 'Stop' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyStop(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Stop' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StopIntegrationTest.testMergeUpdate() {
        Stop obj = dod.getRandomStop();
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stop' failed to provide an identifier", id);
        obj = Stop.findStop(id);
        boolean modified =  dod.modifyStop(obj);
        Integer currentVersion = obj.getVersion();
        Stop merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Stop' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void StopIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", dod.getRandomStop());
        Stop obj = dod.getNewTransientStop(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Stop' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Stop' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Stop' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void StopIntegrationTest.testRemove() {
        Stop obj = dod.getRandomStop();
        Assert.assertNotNull("Data on demand for 'Stop' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Stop' failed to provide an identifier", id);
        obj = Stop.findStop(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Stop' with identifier '" + id + "'", Stop.findStop(id));
    }
    
}
