// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.h4mu.kontroll.domain;

import io.github.h4mu.kontroll.domain.StopDataOnDemand;
import io.github.h4mu.kontroll.domain.StopTime;
import io.github.h4mu.kontroll.domain.StopTimeDataOnDemand;
import io.github.h4mu.kontroll.domain.TripDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect StopTimeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: StopTimeDataOnDemand: @Component;
    
    private Random StopTimeDataOnDemand.rnd = new SecureRandom();
    
    private List<StopTime> StopTimeDataOnDemand.data;
    
    @Autowired
    StopDataOnDemand StopTimeDataOnDemand.stopDataOnDemand;
    
    @Autowired
    TripDataOnDemand StopTimeDataOnDemand.tripDataOnDemand;
    
    public StopTime StopTimeDataOnDemand.getNewTransientStopTime(int index) {
        StopTime obj = new StopTime();
        setSequence(obj, index);
        return obj;
    }
    
    public void StopTimeDataOnDemand.setSequence(StopTime obj, int index) {
        int sequence = index;
        obj.setSequence(sequence);
    }
    
    public StopTime StopTimeDataOnDemand.getSpecificStopTime(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        StopTime obj = data.get(index);
        Integer id = obj.getId();
        return StopTime.findStopTime(id);
    }
    
    public StopTime StopTimeDataOnDemand.getRandomStopTime() {
        init();
        StopTime obj = data.get(rnd.nextInt(data.size()));
        Integer id = obj.getId();
        return StopTime.findStopTime(id);
    }
    
    public boolean StopTimeDataOnDemand.modifyStopTime(StopTime obj) {
        return false;
    }
    
    public void StopTimeDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = StopTime.findStopTimeEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'StopTime' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<StopTime>();
        for (int i = 0; i < 10; i++) {
            StopTime obj = getNewTransientStopTime(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
