// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.h4mu.kontroll.domain;

import io.github.h4mu.kontroll.domain.Trip;
import io.github.h4mu.kontroll.domain.TripDataOnDemand;
import io.github.h4mu.kontroll.domain.TripIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TripIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TripIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TripIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TripIntegrationTest: @Transactional;
    
    @Autowired
    TripDataOnDemand TripIntegrationTest.dod;
    
    @Test
    public void TripIntegrationTest.testCountTrips() {
        Assert.assertNotNull("Data on demand for 'Trip' failed to initialize correctly", dod.getRandomTrip());
        long count = Trip.countTrips();
        Assert.assertTrue("Counter for 'Trip' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TripIntegrationTest.testFindTrip() {
        Trip obj = dod.getRandomTrip();
        Assert.assertNotNull("Data on demand for 'Trip' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trip' failed to provide an identifier", id);
        obj = Trip.findTrip(id);
        Assert.assertNotNull("Find method for 'Trip' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Trip' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TripIntegrationTest.testFindTripEntries() {
        Assert.assertNotNull("Data on demand for 'Trip' failed to initialize correctly", dod.getRandomTrip());
        long count = Trip.countTrips();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Trip> result = Trip.findTripEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Trip' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Trip' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TripIntegrationTest.testFlush() {
        Trip obj = dod.getRandomTrip();
        Assert.assertNotNull("Data on demand for 'Trip' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trip' failed to provide an identifier", id);
        obj = Trip.findTrip(id);
        Assert.assertNotNull("Find method for 'Trip' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTrip(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Trip' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TripIntegrationTest.testMergeUpdate() {
        Trip obj = dod.getRandomTrip();
        Assert.assertNotNull("Data on demand for 'Trip' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trip' failed to provide an identifier", id);
        obj = Trip.findTrip(id);
        boolean modified =  dod.modifyTrip(obj);
        Integer currentVersion = obj.getVersion();
        Trip merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Trip' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TripIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Trip' failed to initialize correctly", dod.getRandomTrip());
        Trip obj = dod.getNewTransientTrip(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Trip' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Trip' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Trip' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TripIntegrationTest.testRemove() {
        Trip obj = dod.getRandomTrip();
        Assert.assertNotNull("Data on demand for 'Trip' failed to initialize correctly", obj);
        Integer id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Trip' failed to provide an identifier", id);
        obj = Trip.findTrip(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Trip' with identifier '" + id + "'", Trip.findTrip(id));
    }
    
}
