// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.h4mu.kontroll.domain;

import io.github.h4mu.kontroll.domain.Route;

privileged aspect Route_Roo_JavaBean {
    
    public String Route.getShortName() {
        return this.shortName;
    }
    
    public void Route.setShortName(String shortName) {
        this.shortName = shortName;
    }
    
}
