// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.h4mu.kontroll.domain;

import io.github.h4mu.kontroll.domain.Stop;

privileged aspect Stop_Roo_JavaBean {
    
    public String Stop.getName() {
        return this.name;
    }
    
    public void Stop.setName(String name) {
        this.name = name;
    }
    
}
