// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package io.github.h4mu.kontroll.domain;

import io.github.h4mu.kontroll.domain.Trip;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Trip_Roo_Configurable {
    
    declare @type: Trip: @Configurable;
    
}
